innovationacademy-kr/42cabi_admin

- backend/app.js
> ✅ 코드리뷰 테스트

- backend/app.js
> Backend 이슈 closed test

- backend/app.js
> ✅ 코드리뷰 테스트 #4

- backend/app.js
> :white_check_mark: 깃 테스트용 풀리퀘

- backend/app.js
- backend/routes/query.js
> ✨ 검색 기능 api 구현

- frontend/src/Components/ButtonSet.tsx
- frontend/src/Components/CabinetDetail.tsx
- frontend/src/Components/NoPrevLog.tsx
- frontend/src/Components/Toast.tsx
- frontend/src/Components/ToastStyleComponent.ts
- frontend/src/Components/UserDetail.tsx
- frontend/src/Modals/ActivationModal.tsx
- frontend/src/Modals/ModalStyleComponent.ts
- frontend/src/Modals/ReturnModal.tsx
- frontend/src/Pages/SearchDashboard.tsx
- frontend/src/Tables/prevCabinetTableStruct.ts
- frontend/src/Tables/prevUserTableStruct.ts
로딩 return 없애고 조건별 return으로 변경 => (불필요한 컴포넌트가 잠깐동안 출력되는 현상이 줄었습니다.)
인트라 아이디 복사 버튼 추가
Toast Notification 적용(버튼 사용 시)
캐비넷 상세 페이지에 현재 활성화/비활성화 상태 표시
모달 컴포넌트 반응형 뷰 설정
기타 자잘한 용어 수정
> Search tap

- frontend/src/Charts/FloorStateChart.tsx
- frontend/src/Charts/TotalStateChart.tsx
- frontend/src/Components/NavBar.tsx
- *Chart.tsx : 테스트 코드 삭제 및 try-catch문 추가
데이터를 불러올 수 없는 경우 차트 대신 렌더링 할 컴포넌트 추가
- NavBar.tsx : '현황' 메뉴의 이름을 '연체/고장'으로 수정. letter-spacing 디자인에 대해 의논 필요해 보임(...)
> :zap: axios 부분에 try-catch 추가

- frontend/src/Pages/Login.tsx
- background를 보라색으로 두고 나머지 요소들을 흰색으로 수정
- 아이디 input의 placeholder를 ID로 수정
> :lipstick: 로그인 페이지 디자인 수정

- frontend/public/index.html
- frontend/public/manifest.json
- frontend/src/Components/Footer.tsx
- frontend/src/Components/Logout.tsx
- frontend/src/Components/NavBar.tsx
- frontend/src/Modals/ActivationModal.tsx
- frontend/src/Modals/ReturnModal.tsx
- frontend/src/Pages/Login.tsx
- 로그아웃 버튼
- Footer 내용 수정
- 웹 페이지 이름, 아이콘 변경
- Return API token header 추가
- Activation API post -> patch
> Status tap

- frontend/src/Charts/FloorStateChart.tsx
- frontend/src/Charts/TotalStateChart.tsx
- frontend/src/Components/SearchBar.tsx
- frontend/src/Modals/ActivationModal.tsx
- frontend/src/Modals/ReturnModal.tsx
- frontend/src/Networks/APIType.ts
- frontend/src/Pages/Login.tsx
- frontend/src/Pages/SearchDashboard.tsx
- frontend/src/Pages/Status.tsx
- frontend/src/index.tsx
- axiosFormat에 error response status code에 따라 처리하는 부분을 합쳐놨습니다.
- 로그인 한 상태에서도 로그인 페이지로 이동할 수 있어서 해당 부분 수정했습니다.
- StrictMode 다시 살렸습니다.
> :art: Add error handling to axiosFormat, Check token in login page #51

- frontend/public/index.html
- frontend/src/Components/CabinetDetail.tsx
- frontend/src/Components/NavBar.tsx
- frontend/src/Components/SearchBar.tsx
- frontend/src/Components/UserDetail.tsx
- frontend/src/Modals/ActivationModal.tsx
- frontend/src/Modals/ModalStyleComponent.ts
- frontend/src/Pages/Status.tsx
- frontend/src/Pages/Task.tsx
- frontend/src/Tables/BanCabinetTable.tsx
- frontend/src/Tables/BanUserTable.tsx
- frontend/src/Tables/DisabledTable.tsx
- frontend/src/Tables/ExpiredTable.tsx
- Task : 고장 사물함, 밴 사물함 관리
- 연체/밴 : 연체 유저, 밴 유저 관리
- 각 탭에서 해당 요소 클릭시 우측에서 바로 컨트롤 할 수 있도록 레이아웃 변경
- 모바일 뷰 깨짐 현상 수정
- 모바일에서 input 필드 선택시 확대되는 현상 제거
> Frontend 메뉴 구조 정리

- frontend/public/index.html
- frontend/src/Components/CabinetDetail.tsx
- frontend/src/Components/LentDisabled.tsx
- frontend/src/Components/NavBar.tsx
- frontend/src/Components/UserDetail.tsx
- frontend/src/Pages/Task.tsx
- frontend/src/Tables/BanCabinetTable.tsx
- frontend/src/Tables/BanUserTable.tsx
- frontend/src/Tables/DisabledTable.tsx
- frontend/src/Tables/ExpiredTable.tsx
> 표 페이지당 15->10건 수정, 페이지 순서 변경, 메시지 변경, 모바일 페이지 조정, 오타 수정

- frontend/src/Components/ButtonSet.tsx
- frontend/src/Components/UserDetail.tsx
- frontend/src/Modals/ReturnModal.tsx
- frontend/src/Pages/Status.tsx
- frontend/src/Tables/BanCabinetTable.tsx
- frontend/src/Tables/BanUserTable.tsx
- frontend/src/Tables/DisabledTable.tsx
- frontend/src/Tables/ExpiredTable.tsx
- frontend/src/Tables/banUserTableStruct.ts
- frontend/src/Tables/disabledTableStruct.ts
- frontend/src/Tables/prevCabinetTableStruct.ts
*버그 수정
- 표에서 항목 클릭할 때 마다 표가 1페이지로 돌아가는 현상
- 연체/밴 페이지에서 연체자를 클릭하고 반납했을 때 에러 페이지로 넘어가는 현상
- 연체/밴 페이지에서 연체자를 클릭하고 반납했을 때 표가 업데이트 되지 않는 현상
*표 수정
- 고장 사물함 -> 고장 발생일 제거 (API에서 주지않는 값)
> FrontEnd 버그 수정

- backend/src/return/repository/rawquery.return.repository.ts
- backend/src/return/repository/return.repository.interface.ts
- backend/src/return/repository/return.repository.ts
- backend/src/return/return.module.ts
- backend/src/return/return.service.ts
- backend/src/search/repository/rawquery-search.repository.ts
- backend/src/search/repository/search.repository.interface.ts
- backend/src/search/repository/search.repository.ts
- backend/src/search/search.module.ts
- backend/src/search/search.service.ts
- backend/src/user/repository/rawquery-user.repository.ts
- backend/src/user/repository/user.repository.interface.ts
- backend/src/user/repository/user.repository.ts
- backend/src/user/user.module.ts
- backend/src/user/user.service.ts
#106 이슈에 따라 세가지 모듈에 대한 리포지토리에 대해 TypeORM 구현체를 구현하였습니다.
트랜잭션 처리 이외에 별다른 특이사항은 없습니다.
> feat: #106 add TyprORM Repositories (return, search, user)

- frontend/src/Modals/ReturnModal.tsx
- frontend/src/Pages/SearchDashboard.tsx
- frontend/src/type.ts
현재 페이지의 쿼리 스트링에 따라서 반납 후 정보가 업데이트 될 수 있도록 수정했습니다.
> FIX: Search - print undefined after return

- backend/src/activation/repository/activation.repository.ts
- backend/src/search/repository/search.repository.ts
- backend/src/search/search.module.ts
- backend/src/search/search.service.ts
- frontend/package-lock.json
fix bug not show intra_id when search #117
> :bug: fix bug not show intra_id when search #117

- backend/src/search/repository/search.repository.ts
FIX: 대여 중이지 않은 사물함과 없는 사물함 구분 필요 #116
> :bug: FIX: 대여 중이지 않은 사물함과 없는 사물함 구분 필요 #116

- backend/src/activation/repository/activation.repository.ts
- backend/src/search/repository/search.repository.ts
- backend/src/search/search.controller.ts
- backend/src/search/search.service.ts
fix bug not show result when search deleted user #123
> :bug: fix bug not show result when search deleted user #123

- backend/src/cabinet/cabinet.module.ts
- backend/src/cabinet/cabinet.service.ts
- backend/src/cabinet/repository/cabinet.repository.interface.ts
- backend/src/cabinet/repository/cabinet.repository.ts
- backend/src/return/return.controller.ts
- backend/src/return/return.module.ts
- backend/src/return/return.service.ts
#124 일괄 반납 기능을 추가했습니다.
섹션별로 반납이 가능합니다.
> feat: sectionReturn #124

- backend/src/entities/user.entity.ts
- backend/src/enums/user.state.type.enum.ts
- backend/src/search/repository/rawquery-search.repository.ts
> delete user state #137

- backend/src/search/repository/search.repository.ts
> :ambulance: fix where condition in getLentByIntraId #122

- backend/package-lock.json
- backend/package.json
- backend/src/app.module.ts
- backend/src/main.ts
admin에서 `transactional` 데코레이터 사용을 위한 설정 코드를 추가했습니다.
> :package: add transactional setting code #136

- backend/src/main.ts
- backend/src/v3/log/dto/cabinet-lent-log.dto.ts
- backend/src/v3/log/dto/log.pagenation.dto.ts
- backend/src/v3/log/log.controller.ts
- backend/src/v3/log/log.module.ts
- backend/src/v3/log/log.service.ts
- backend/src/v3/log/repository/log.repository.interface.ts
- backend/src/v3/log/repository/log.repository.ts
- backend/src/v3/search/dto/blocked-user-info.dto.ts
- backend/src/v3/search/dto/blocked-user-info.pagenation.dto.ts
- backend/src/v3/search/dto/broken-cabinet-info.dto.ts
- backend/src/v3/search/dto/broken-cabinet-info.pagenation.dto.ts
- backend/src/v3/search/dto/cabinet-info.dto.ts
- backend/src/v3/search/dto/cabinet-info.pagenation.dto.ts
- backend/src/v3/search/dto/lent.dto.ts
- backend/src/v3/search/dto/user-info.dto.ts
- backend/src/v3/search/dto/user-info.pagenation.dto.ts
- backend/src/v3/search/repository/search.repository.interface.ts
- backend/src/v3/search/repository/search.repository.ts
- backend/src/v3/search/search.controller.ts
- backend/src/v3/search/search.module.ts
- backend/src/v3/search/search.service.ts
- backend/src/v3/v3.module.ts
로그와 검색 모듈을 추가하였습니다.
- Swagger에 JWT Authorization 정보를 추가하였습니다.
- 페이지네이션 구현을 위해 로그는 쿼리빌더, 검색은 find 메소드를 사용하였습니다.
> #113 로그, 검색 모듈 추가

- backend/src/v3/cabinet/dto/cabinet.dto.ts
- backend/src/v3/cabinet/repository/cabinet.repository.ts
cabinet 정보를 넘겨줄 때 status note를 넘겨주지 않는 오류를 발견해서 고쳤습니다!
> Be v3/cabinet

- frontend/src/Components/CabinetDetail.tsx
- frontend/src/type.ts
- #158 
- 동아리 사물함 정보 확인을 위해 임시로 수정했습니다.
> FEAT: 검색 페이지 동아리 사물함 정보 표시
